# --- ESTETICA E BORDI INTERNI ---
window_padding_width 15
placement_strategy center
hide_window_decorations yes

# --- TEMA COLORI (DARK TOKYO NIGHT) ---
# foreground            #c0caf5
# background            #1a1b26
# selection_foreground  #c0caf5
# selection_background  #283457

# Cursore
# cursor                #c0caf5
# cursor_text_color     #1a1b26

# Colori Normali
# color0 #15161e
# color1 #f7768e
# color2 #9ece6a
# color3 #e0af68
# color4 #7aa2f7
# color5 #bb9af7
# color6 #7dcfff
# color7 #a9b1d6

# Colori Bright
# color8 #414868
# color9 #f7768e
# color10 #9ece6a
# color11 #e0af68
# color12 #7aa2f7
# color13 #bb9af7
# color14 #7dcfff
# color15 #c0caf5

# --- ANIMAZIONI CURSORE (STILE GHOSTTY) ---
cursor_shape block
cursor_blink_interval 0
shell_integration enabled
cursor_trail 3
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

# --- BORDI FINESTRA (SPLIT) ---
# active_border_color   #7aa2f7
# inactive_border_color #353D57
window_border_width   1pt

# --- TRASPARENZA ---
#background_opacity 0.95
background_opacity 0.81
background_blur 1

# --- FONT (Assicurati di avere una Nerd Font installata) ---
font_family      JetBrainsMono Nerd Font
font_size        11.0

# Use fish shell
shell /usr/bin/fish --login


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME